
{{- if .Values.argocd.giropopsSenhas.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: "giropopsSenhas.replicas"
        value: "{{ .Values.argocd.giropopsSenhas.replicas }}"
    path: app/giropops-senhas/helm
    repoURL: https://github.com/k0ody/Descomplicando-GitOps-ArgoCD.git
    targetRevision: feat/day2
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}