apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: app/app-of-apps
    helm:
      parameters:
      - name: "argocd.giropopsSenhas.enabled"
        value: "true"
      - name: "argocd.randomlogger.enabled"
        value: "true"
    repoURL: 'https://github.com/k0ody/Descomplicando-GitOps-ArgoCD.git'
    targetRevision: feat/day2
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - prune=true
    automated:
      selfHeal: true
      prune: true