apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: giropops-senhas
  source:
    repoURL: 'https://github.com/k0ody/Descomplicando-GitOps-ArgoCD.git'
    targetRevision: feat/day2
    path: app/giropops-senhas/helm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true